package com.raymond.domain;

// Generated 2011-11-5 17:09:59 by Hibernate Tools 3.2.4.GA

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import br.com.jsigner.annotations.Domain;

/**
 * BankAccounts generated by hbm2java
 */
@Domain(value = { "raymond-domain" })
@Entity
@Table(name = "BankAccounts", schema = "RAYMOND_APP")
public class BankAccounts implements java.io.Serializable {

	private int id;
	private Dealers dealers;
	private Serializable userName;
	private Serializable name;
	private String account;

	public BankAccounts() {
	}

	public BankAccounts(int id, Dealers dealers, Serializable userName,
			Serializable name, String account) {
		this.id = id;
		this.dealers = dealers;
		this.userName = userName;
		this.name = name;
		this.account = account;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DealerID", nullable = false)
	public Dealers getDealers() {
		return this.dealers;
	}

	public void setDealers(Dealers dealers) {
		this.dealers = dealers;
	}

	@Column(name = "UserName", nullable = false)
	public Serializable getUserName() {
		return this.userName;
	}

	public void setUserName(Serializable userName) {
		this.userName = userName;
	}

	@Column(name = "Name", nullable = false)
	public Serializable getName() {
		return this.name;
	}

	public void setName(Serializable name) {
		this.name = name;
	}

	@Column(name = "Account", nullable = false, length = 50)
	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

}
