package com.raymond.domain;

// Generated 2011-11-5 17:09:59 by Hibernate Tools 3.2.4.GA

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import br.com.jsigner.annotations.Domain;

/**
 * Dealers generated by hbm2java
 */
@Domain(value = { "raymond-domain" })
@Entity
@Table(name = "Dealers", schema = "RAYMOND_APP")
public class Dealers implements java.io.Serializable {

	private int id;
	private Serializable name;
	private Serializable address;
	private String phone;
	private String website;
	private String fax;
	private Serializable headName;
	private String headPhone;
	private Serializable businessName;
	private String businessPhone;
	private String businessQq;
	private String businessMsn;
	private String businessEmail;
	private Serializable status;
	private Set<Products> productses = new HashSet<Products>(0);
	private Set<BankAccounts> bankAccountses = new HashSet<BankAccounts>(0);
	private Set<ProductTypes> productTypeses = new HashSet<ProductTypes>(0);

	public Dealers() {
	}

	public Dealers(int id, Serializable name, Serializable address,
			String phone, String fax, Serializable headName, String headPhone,
			Serializable businessName, String businessPhone, Serializable status) {
		this.id = id;
		this.name = name;
		this.address = address;
		this.phone = phone;
		this.fax = fax;
		this.headName = headName;
		this.headPhone = headPhone;
		this.businessName = businessName;
		this.businessPhone = businessPhone;
		this.status = status;
	}

	public Dealers(int id, Serializable name, Serializable address,
			String phone, String website, String fax, Serializable headName,
			String headPhone, Serializable businessName, String businessPhone,
			String businessQq, String businessMsn, String businessEmail,
			Serializable status, Set<Products> productses,
			Set<BankAccounts> bankAccountses, Set<ProductTypes> productTypeses) {
		this.id = id;
		this.name = name;
		this.address = address;
		this.phone = phone;
		this.website = website;
		this.fax = fax;
		this.headName = headName;
		this.headPhone = headPhone;
		this.businessName = businessName;
		this.businessPhone = businessPhone;
		this.businessQq = businessQq;
		this.businessMsn = businessMsn;
		this.businessEmail = businessEmail;
		this.status = status;
		this.productses = productses;
		this.bankAccountses = bankAccountses;
		this.productTypeses = productTypeses;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "Name", nullable = false)
	public Serializable getName() {
		return this.name;
	}

	public void setName(Serializable name) {
		this.name = name;
	}

	@Column(name = "Address", nullable = false)
	public Serializable getAddress() {
		return this.address;
	}

	public void setAddress(Serializable address) {
		this.address = address;
	}

	@Column(name = "Phone", nullable = false, length = 100)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "Website", length = 100)
	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	@Column(name = "Fax", nullable = false, length = 100)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "HeadName", nullable = false)
	public Serializable getHeadName() {
		return this.headName;
	}

	public void setHeadName(Serializable headName) {
		this.headName = headName;
	}

	@Column(name = "HeadPhone", nullable = false, length = 50)
	public String getHeadPhone() {
		return this.headPhone;
	}

	public void setHeadPhone(String headPhone) {
		this.headPhone = headPhone;
	}

	@Column(name = "BusinessName", nullable = false)
	public Serializable getBusinessName() {
		return this.businessName;
	}

	public void setBusinessName(Serializable businessName) {
		this.businessName = businessName;
	}

	@Column(name = "BusinessPhone", nullable = false, length = 50)
	public String getBusinessPhone() {
		return this.businessPhone;
	}

	public void setBusinessPhone(String businessPhone) {
		this.businessPhone = businessPhone;
	}

	@Column(name = "BusinessQQ", length = 50)
	public String getBusinessQq() {
		return this.businessQq;
	}

	public void setBusinessQq(String businessQq) {
		this.businessQq = businessQq;
	}

	@Column(name = "BusinessMSN", length = 50)
	public String getBusinessMsn() {
		return this.businessMsn;
	}

	public void setBusinessMsn(String businessMsn) {
		this.businessMsn = businessMsn;
	}

	@Column(name = "BusinessEmail", length = 100)
	public String getBusinessEmail() {
		return this.businessEmail;
	}

	public void setBusinessEmail(String businessEmail) {
		this.businessEmail = businessEmail;
	}

	@Column(name = "Status", nullable = false)
	public Serializable getStatus() {
		return this.status;
	}

	public void setStatus(Serializable status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dealers")
	public Set<Products> getProductses() {
		return this.productses;
	}

	public void setProductses(Set<Products> productses) {
		this.productses = productses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dealers")
	public Set<BankAccounts> getBankAccountses() {
		return this.bankAccountses;
	}

	public void setBankAccountses(Set<BankAccounts> bankAccountses) {
		this.bankAccountses = bankAccountses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dealers")
	public Set<ProductTypes> getProductTypeses() {
		return this.productTypeses;
	}

	public void setProductTypeses(Set<ProductTypes> productTypeses) {
		this.productTypeses = productTypeses;
	}

}
