package com.raymond.domain;

// Generated 2011-11-5 17:09:59 by Hibernate Tools 3.2.4.GA

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PdtnumberPrices generated by hbm2java
 */
@Entity
@Table(name = "PDTNumberPrices", schema = "RAYMOND_APP")
public class PdtnumberPrices implements java.io.Serializable {

	private int id;
	private BigDecimal productId;
	private Serializable type;
	private BigDecimal startNumber;
	private BigDecimal endNumber;
	private BigDecimal price;

	public PdtnumberPrices() {
	}

	public PdtnumberPrices(int id, BigDecimal productId, Serializable type,
			BigDecimal startNumber, BigDecimal endNumber, BigDecimal price) {
		this.id = id;
		this.productId = productId;
		this.type = type;
		this.startNumber = startNumber;
		this.endNumber = endNumber;
		this.price = price;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "ProductID", nullable = false, precision = 22, scale = 0)
	public BigDecimal getProductId() {
		return this.productId;
	}

	public void setProductId(BigDecimal productId) {
		this.productId = productId;
	}

	@Column(name = "Type", nullable = false)
	public Serializable getType() {
		return this.type;
	}

	public void setType(Serializable type) {
		this.type = type;
	}

	@Column(name = "StartNumber", nullable = false, precision = 22, scale = 0)
	public BigDecimal getStartNumber() {
		return this.startNumber;
	}

	public void setStartNumber(BigDecimal startNumber) {
		this.startNumber = startNumber;
	}

	@Column(name = "EndNumber", nullable = false, precision = 22, scale = 0)
	public BigDecimal getEndNumber() {
		return this.endNumber;
	}

	public void setEndNumber(BigDecimal endNumber) {
		this.endNumber = endNumber;
	}

	@Column(name = "Price", nullable = false, precision = 8)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

}
