package com.raymond.domain;

// Generated 2011-11-5 17:09:59 by Hibernate Tools 3.2.4.GA

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PdtPkgPrices generated by hbm2java
 */
@Entity
@Table(name = "PDT_PKG_Prices", schema = "RAYMOND_APP")
public class PdtPkgPrices implements java.io.Serializable {

	private int id;
	private BigDecimal productId;
	private Serializable type;
	private Serializable packageType;
	private BigDecimal price;

	public PdtPkgPrices() {
	}

	public PdtPkgPrices(int id, BigDecimal productId, Serializable type,
			Serializable packageType, BigDecimal price) {
		this.id = id;
		this.productId = productId;
		this.type = type;
		this.packageType = packageType;
		this.price = price;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "ProductID", nullable = false, precision = 22, scale = 0)
	public BigDecimal getProductId() {
		return this.productId;
	}

	public void setProductId(BigDecimal productId) {
		this.productId = productId;
	}

	@Column(name = "Type", nullable = false)
	public Serializable getType() {
		return this.type;
	}

	public void setType(Serializable type) {
		this.type = type;
	}

	@Column(name = "PackageType", nullable = false)
	public Serializable getPackageType() {
		return this.packageType;
	}

	public void setPackageType(Serializable packageType) {
		this.packageType = packageType;
	}

	@Column(name = "Price", nullable = false, precision = 8)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

}
