package com.raymond.domain;

// Generated 2011-11-5 17:09:59 by Hibernate Tools 3.2.4.GA

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import br.com.jsigner.annotations.Domain;

/**
 * ProductTypes generated by hbm2java
 */
@Domain(value = { "raymond-domain" })
@Entity
@Table(name = "ProductTypes", schema = "RAYMOND_APP")
public class ProductTypes implements java.io.Serializable {

	private int id;
	private Dealers dealers;
	private Serializable name;
	private Set<Products> productses = new HashSet<Products>(0);

	public ProductTypes() {
	}

	public ProductTypes(int id, Dealers dealers, Serializable name) {
		this.id = id;
		this.dealers = dealers;
		this.name = name;
	}

	public ProductTypes(int id, Dealers dealers, Serializable name,
			Set<Products> productses) {
		this.id = id;
		this.dealers = dealers;
		this.name = name;
		this.productses = productses;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DealerID", nullable = false)
	public Dealers getDealers() {
		return this.dealers;
	}

	public void setDealers(Dealers dealers) {
		this.dealers = dealers;
	}

	@Column(name = "Name", nullable = false)
	public Serializable getName() {
		return this.name;
	}

	public void setName(Serializable name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productTypes")
	public Set<Products> getProductses() {
		return this.productses;
	}

	public void setProductses(Set<Products> productses) {
		this.productses = productses;
	}

}
