package com.raymond.domain;

// Generated 2011-11-5 17:09:59 by Hibernate Tools 3.2.4.GA

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import br.com.jsigner.annotations.Domain;

/**
 * Products generated by hbm2java
 */
@Domain(value = { "raymond-domain" })
@Entity
@Table(name = "Products", schema = "RAYMOND_APP")
public class Products implements java.io.Serializable {

	private int id;
	private ProductTypes productTypes;
	private Dealers dealers;
	private Serializable name;
	private String model;
	private String productSize;
	private String packageSize;
	private String packageNumber;
	private BigDecimal logoPrice;
	private BigDecimal customSafeCycle;
	private Set<ProductKeywords> productKeywordses = new HashSet<ProductKeywords>(
			0);
	private Set<ProductImages> productImageses = new HashSet<ProductImages>(0);

	public Products() {
	}

	public Products(int id, ProductTypes productTypes, Dealers dealers,
			Serializable name) {
		this.id = id;
		this.productTypes = productTypes;
		this.dealers = dealers;
		this.name = name;
	}

	public Products(int id, ProductTypes productTypes, Dealers dealers,
			Serializable name, String model, String productSize,
			String packageSize, String packageNumber, BigDecimal logoPrice,
			BigDecimal customSafeCycle, Set<ProductKeywords> productKeywordses,
			Set<ProductImages> productImageses) {
		this.id = id;
		this.productTypes = productTypes;
		this.dealers = dealers;
		this.name = name;
		this.model = model;
		this.productSize = productSize;
		this.packageSize = packageSize;
		this.packageNumber = packageNumber;
		this.logoPrice = logoPrice;
		this.customSafeCycle = customSafeCycle;
		this.productKeywordses = productKeywordses;
		this.productImageses = productImageses;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TypeID", nullable = false)
	public ProductTypes getProductTypes() {
		return this.productTypes;
	}

	public void setProductTypes(ProductTypes productTypes) {
		this.productTypes = productTypes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DealerID", nullable = false)
	public Dealers getDealers() {
		return this.dealers;
	}

	public void setDealers(Dealers dealers) {
		this.dealers = dealers;
	}

	@Column(name = "Name", nullable = false)
	public Serializable getName() {
		return this.name;
	}

	public void setName(Serializable name) {
		this.name = name;
	}

	@Column(name = "Model", length = 50)
	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	@Column(name = "ProductSize", length = 50)
	public String getProductSize() {
		return this.productSize;
	}

	public void setProductSize(String productSize) {
		this.productSize = productSize;
	}

	@Column(name = "PackageSize", length = 50)
	public String getPackageSize() {
		return this.packageSize;
	}

	public void setPackageSize(String packageSize) {
		this.packageSize = packageSize;
	}

	@Column(name = "PackageNumber", length = 50)
	public String getPackageNumber() {
		return this.packageNumber;
	}

	public void setPackageNumber(String packageNumber) {
		this.packageNumber = packageNumber;
	}

	@Column(name = "LogoPrice", precision = 8)
	public BigDecimal getLogoPrice() {
		return this.logoPrice;
	}

	public void setLogoPrice(BigDecimal logoPrice) {
		this.logoPrice = logoPrice;
	}

	@Column(name = "CustomSafeCycle", precision = 22, scale = 0)
	public BigDecimal getCustomSafeCycle() {
		return this.customSafeCycle;
	}

	public void setCustomSafeCycle(BigDecimal customSafeCycle) {
		this.customSafeCycle = customSafeCycle;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "products")
	public Set<ProductKeywords> getProductKeywordses() {
		return this.productKeywordses;
	}

	public void setProductKeywordses(Set<ProductKeywords> productKeywordses) {
		this.productKeywordses = productKeywordses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "products")
	public Set<ProductImages> getProductImageses() {
		return this.productImageses;
	}

	public void setProductImageses(Set<ProductImages> productImageses) {
		this.productImageses = productImageses;
	}

}
